### ISSUE TITLE
Исправить алгоритм

### ISSUE THREAD

**Issue by Kasiwadzaki** [Alexiusss/uno_soft_test_task#1]
Добрый день, меня зовут Вадим, я представитель компании Uno-Soft.

В вашей программе есть несколько серьезных недочетов:
1) В аргументы мы должны принимать файл который должны посчитать, а не тот который должен получиться(Выходной файл можно просто создавать рядом с jar)
2) Алгоритм падает по OutOfMemoryError на файле  https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-4.txt.gz
3) На файле https://github.com/PeacockTeam/new-job/blob/master/lng.7z ответ неверный 

Ждем результаты правок до 27.11.2023 включительно

**Comment by Alexiusss** [comment]
Добрый день, Вадим.

1. Т.к. там 2 разные реализации, то можно файлы которые нужно посчитать рядом с jar класть?
2. Да действительно, в последних изменениях делал больший акцент на большом файле и jar с ограничением по потреблению памяти запускал только на нем. А маленький файл проверял только в IDE без ограничений.
3. Что именно неверно в ответе? Общее количество или состав групп? Предварительно мне писали, что ответы верные по обоим.

**Comment by Kasiwadzaki** [comment]
1. Насчет местонахождения файла по желанию, акцент на этом не делается, но если брать удобство, то абсолютный путь выглядит куда лучше относительного
3. Неверный ответ, это значит неверное количество групп по результату выполнения программы

**Comment by Alexiusss** [comment]
Здравстуйте, Вадим.
Недочеты исправил.
